### ISSUE TITLE
Unrecognised run types are ignored

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#108]
I think they should be exceptions.

**Comment by squaregoldfish** [comment]
They should also be checked at file upload time, so the file is rejected immediately

**Comment by jonasfh** [comment]
Discussing this with Rocio, we decided that the user will need to revisit the instruments - page to add a new run-type there.

**Comment by squaregoldfish** [comment]
What's the reasoning?

**Comment by jonasfh** [comment]
There are several reasons: 
- Rocio thinks it is good for the scientists to have to consider their decisions, not just press IGNORE
- I like the idea because it is much easier to implement
- And: most possibly this don't happen to often, so it will not be a big problem to have to do it this way
- I initially asked Rocio her opinion, as I did not see where to logically add the UI parts for this
